id = "oberon"
name = "Oberon"
version = "0.0.1"
schema_version = 1
authors = ["Knyaz"]
description = "Oberon-07 language support"

[grammars.oberon07]
repository = "https://github.com/geekstakulus/tree-sitter-oberon-07"
rev = "162c3432ed2584efa0bca4fd10e5cb4d3195f4a6"
